---
title: "Biodiversidad de la Gran Área Metropolitana"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

```{r setup, include=FALSE}
#-------------------- Paquetes --------------------

library(flexdashboard)
library(dplyr)
library(sf)
library(leaflet)
library(leafem)
library(esri2sf)
library(plotly)

```

Row {data-height=10}
-----------------------------------------------------------------------
### **Servicio ecosistémico de soporte: Hábitat para la biodiversidad (riqueza de especies). Fuente de los datos: [Infraestructura Global de Información en Biodiversidad (GBIF)](https://www.gbif.org/occurrence/download/0002762-200127171203522). Se incluyen los registros de presencia de especies identificadas entre 2000 y 2020.**

Row {data-height=800}
-----------------------------------------------------------------------

### Registros de presencia de especies {data-width=600}
```{r include=FALSE}

#--------- URL de geoservicios y datos ------------

url_agfs_limite_gam <-
  "https://services9.arcgis.com/RrvMEynxDB8hycVO/arcgis/rest/services/gam_limite_gam/FeatureServer/0"

url_csv_registros_presencia <-
  "https://raw.githubusercontent.com/atlas-servicios-ecosistemicos-gam/datos-biodiversidad/main/gam/gam-registros-presencia-chordata-plantae.csv"

#------------------- Constantes -------------------

# Año límite inferior del periodo de datos a considerar
ANYO_LIMITE_INFERIOR = "2000"

#---------------- Objetos sf y df -----------------

# Límite de la GAM
sf_limite_gam <- 
  esri2sf(url_agfs_limite_gam)

# Límite de la GAM (reproyectada a Web Mercator)
sf_limite_gam_web <- 
  sf_limite_gam %>%
  st_transform(3857)

# Capa vectorial de puntos de registros de presencia
sf_registros_presencia <- 
  st_read(
    url_csv_registros_presencia, 
    options = c("X_POSSIBLE_NAMES=decimalLongitude","Y_POSSIBLE_NAMES=decimalLatitude")
  )  %>%
  filter((taxonRank == "SPECIES" | taxonRank == "SUBSPECIES" | taxonRank == "VARIETY" | taxonRank == "FORM") & year >= ANYO_LIMITE_INFERIOR)


# AVES
# Registros de presencia de aves agrupados por especie
df_registros_presencia_aves_agrupados_por_especie <-
  sf_registros_presencia %>%
  st_drop_geometry() %>%
  filter(class == "Aves") %>%
  dplyr::count(species)

# Cantidad de especies de aves
especies_aves <-
  nrow(df_registros_presencia_aves_agrupados_por_especie)


# ANFIBIOS
# Registros de presencia de anfibios agrupados por especie
df_registros_presencia_amphibia_agrupados_por_especie <-
  sf_registros_presencia %>%
  st_drop_geometry() %>%
  filter(class == "Amphibia") %>%
  dplyr::count(species)

# Cantidad de especies de anfibios
especies_amphibia <-
  nrow(df_registros_presencia_amphibia_agrupados_por_especie)


# REPTILES
# Registros de presencia de reptiles agrupados por especie
df_registros_presencia_reptilia_agrupados_por_especie <-
  sf_registros_presencia %>%
  st_drop_geometry() %>%
  filter(class == "Reptilia") %>%
  dplyr::count(species)

# Cantidad de especies de reptiles
especies_reptilia <-
  nrow(df_registros_presencia_reptilia_agrupados_por_especie)


# MAMÍFEROS
# Registros de presencia de mamíferos agrupados por especie
df_registros_presencia_mammalia_agrupados_por_especie <-
  sf_registros_presencia %>%
  st_drop_geometry() %>%
  filter(class == "Mammalia") %>%
  dplyr::count(species)

# Cantidad de especies de mamíferos
especies_mammalia <-
  nrow(df_registros_presencia_mammalia_agrupados_por_especie)


# PLANTAS
# Registros de presencia de plantas agrupados por especie
df_registros_presencia_plantae_agrupados_por_especie <-
  sf_registros_presencia %>%
  st_drop_geometry() %>%
  filter(kingdom == "Plantae") %>%
  dplyr::count(species)

# Cantidad de especies de plantas
especies_plantae <-
  nrow(df_registros_presencia_plantae_agrupados_por_especie)

```

```{r}

#------------------- Mapa ------------------

leaflet() %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group = "OpenStreetMap") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Stamen Toner Lite") %>%
  addProviderTiles(providers$CartoDB.DarkMatter, group = "CartoDB Dark Matter") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Imágenes de ESRI") %>%
  addPolygons(
    data = sf_limite_gam,
    color = "Purple",
    fillColor = "transparent",
    stroke = TRUE,
    weight = 6.0,
    group = "Límite de la GAM"
  ) %>%
  addCircleMarkers(
    data = sf_registros_presencia,
    stroke = F,
    radius = 4,
    fillColor = 'red',
    fillOpacity = 1,
    clusterOptions = markerClusterOptions(),
    popup = paste(sf_registros_presencia$kingdom,
                  sf_registros_presencia$class,
                  sf_registros_presencia$species,
                  sf_registros_presencia$year, 
                  sep = '<br/>'),
    group = "Registros de presencia",
  ) %>%  
  addLayersControl(
    baseGroups = c("OpenStreetMap", "Stamen Toner Lite", "CartoDB Dark Matter", "Imágenes de ESRI"),
    overlayGroups = c("Límite de la GAM", "Registros de presencia de especies"),
    options = layersControlOptions(collapsed = TRUE)    
  ) %>%  
  addScaleBar(
    position = "bottomright",
    options = scaleBarOptions(imperial = FALSE)
  ) %>%
  addMouseCoordinates()
```

### {data-width=400}
```{r}

# Vector de tipos de aves migratorias
categorias <- c("Migrantes continentales", "Migrantes altitudinales", "Residentes")
# Vector de valores
valores <- c(13, 54, 33)
tipos_migratorias <- 
  data.frame(
    categoria = categorias, 
    valor = valores
  )
datos <- tipos_migratorias[,c('categoria', 'valor')]
fig <- plot_ly(datos, labels = ~categorias, values = ~valores, type = 'pie')
fig <- fig %>% layout(title = 'Tipo de aves migratorias',
                      xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                      yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

fig

```

Row {data-height=190}
-----------------------------------------------------------------------

### Aves {.value-box} {data-width=200}
```{r}
valueBox(
  value = "Aves", 
  caption = paste(especies_aves, "especies")
)
```

### Anfibios {.value-box} {data-width=200}
```{r}
valueBox(value = "Anfibios", 
  caption = paste(especies_amphibia, "especies")
)
```

### Reptiles {.value-box} {data-width=200}
```{r}
valueBox(value = "Reptiles", 
  caption = paste(especies_reptilia, "especies")
)
```

### Mamíferos {.value-box} {data-width=200}
```{r}
valueBox(
  value = "Mamíferos",
  caption = paste(especies_mammalia, "especies")
)
```

### Flora {.value-box} {data-width=200}
```{r}
valueBox(value = "Flora", 
  caption = paste(especies_plantae, "especies")
)
```